# オブジェクト指向の活用

## 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。


Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

- Pandas : DataFrame
- matplotlib : pyplot
- scikit-learn : svm

## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。


最低でもそれぞれ5つ以上答えてください。


《ndarrayやstrもインスタンス》


ドットをつけるというと、NumPyのndarrayに対してndarray.shapeやndarray.sum()のような使い方は何度も利用してきたかと思います。これは、ndarrayもインスタンスオブジェクトであり、shapeはインスタンス変数、sumはメソッドだったということです。


Pythonのコードに登場するデータはどれもインスタンスオブジェクトであり、listやstrもメソッドを持ちます。

- メソッド  
    1.mean()  
    2.sum()  
    3.append()  
    4.merge()  
    5.discribe()  
    
- アトリビュード  
    1.shape  
    2.coef_  
    3.classes_  
    4.effective_metric_  
    5.n_sample_fit_  
  
  
## 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。


今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。


インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。

In [1]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X)
        self.var_ = np.var(X)
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / self.var_
        return X_scaled

In [2]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : 2.46
分散 : 3.1744
[[ 0.83165323  0.32762097 -0.33392137 -0.71194556]
 [ 0.76864919  0.17011089 -0.33392137 -0.71194556]
 [ 0.70564516  0.23311492 -0.36542339 -0.71194556]
 [ 0.67414315  0.2016129  -0.30241935 -0.71194556]
 [ 0.80015121  0.35912298 -0.33392137 -0.71194556]
 [ 0.92615927  0.45362903 -0.23941532 -0.64894153]
 [ 0.67414315  0.29611895 -0.33392137 -0.68044355]
 [ 0.80015121  0.29611895 -0.30241935 -0.71194556]
 [ 0.61113911  0.13860887 -0.33392137 -0.71194556]
 [ 0.76864919  0.2016129  -0.30241935 -0.74344758]]


## 【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。


コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。


クラス名や説明文も適切に書き換えてください。

In [3]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    value2 : float or int
        計算したい値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        if (type(value) != int) and (type(value) != float):
            print('入力エラー')
        else:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        
    def pull(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value2
        
    def times(self, value2):
        """
        受け取った引数をself.valueに掛ける
        """
        self.value *= value2
        
    def divide(self, value2):
        """
        受け取った引数をself.valueから割る
        """
        self.value /= value2

In [4]:
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


In [5]:
test = ExampleClass('test')

入力エラー


In [6]:
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.pull(3)
print("value : {}".format(example.value))
example.times(4)
print("value : {}".format(example.value))
example.divide(2)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 5
value : 20
value : 10.0
